risky: false

version: 7.4

preset: laravel

tab-width: 4

use-tabs: false

enabled:
  - "phpdoc_align"

disabled:
  - "unalign_equals"
  - "laravel_phpdoc_separation"
  - "laravel_phpdoc_alignment"

finder:
  exclude:
    - "GPBMetadata"
