<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Account 的信息.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.Account</code>.
 */
class Account extends Message
{
    /**
     * coins标识，目前只有0 一个值
     * Generated from protobuf field <code>int32 currency = 1;</code>.
     */
    protected int $currency = 0;

    /**
     *账户可用余额.
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     */
    protected int $balance = 0;

    /**
     *账户冻结余额.
     * Generated from protobuf field <code>int64 frozen = 3;</code>.
     */
    protected int $frozen = 0;

    /**
     *账户的地址
     * Generated from protobuf field <code>string addr = 4;</code>.
     */
    protected string $addr = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var int $currency
     *          coins标识，目前只有0 一个值
     * @var int|string $balance
     *                 账户可用余额
     * @var int|string $frozen
     *                 账户冻结余额
     * @var string $addr
     *             账户的地址
     *             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * coins标识，目前只有0 一个值
     * Generated from protobuf field <code>int32 currency = 1;</code>.
     *
     * @return int
     */
    public function getCurrency(): int
    {
        return $this->currency;
    }

    /**
     * coins标识，目前只有0 一个值
     * Generated from protobuf field <code>int32 currency = 1;</code>.
     *
     * @param  int  $var
     * @return $this
     * @throws Exception
     */
    public function setCurrency(int $var): Account
    {
        GPBUtil::checkInt32($var);
        $this->currency = $var;

        return $this;
    }

    /**
     *账户可用余额.
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     *
     * @return int
     */
    public function getBalance(): int
    {
        return $this->balance;
    }

    /**
     *账户可用余额.
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setBalance($var): Account
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     *账户冻结余额.
     * Generated from protobuf field <code>int64 frozen = 3;</code>.
     *
     * @return int
     */
    public function getFrozen(): int
    {
        return $this->frozen;
    }

    /**
     *账户冻结余额.
     * Generated from protobuf field <code>int64 frozen = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setFrozen($var): Account
    {
        GPBUtil::checkInt64($var);
        $this->frozen = $var;

        return $this;
    }

    /**
     *账户的地址
     * Generated from protobuf field <code>string addr = 4;</code>.
     *
     * @return string
     */
    public function getAddr(): string
    {
        return $this->addr;
    }

    /**
     *账户的地址
     * Generated from protobuf field <code>string addr = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setAddr(string $var): Account
    {
        GPBUtil::checkString($var, true);
        $this->addr = $var;

        return $this;
    }
}
