<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.AddrOverview</code>.
 */
class AddrOverview extends Message
{
    /**
     * Generated from protobuf field <code>int64 reciver = 1;</code>.
     */
    protected int $reciver = 0;

    /**
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     */
    protected int $balance = 0;

    /**
     * Generated from protobuf field <code>int64 txCount = 3;</code>.
     */
    protected int $txCount = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var int|string $reciver
     * @var int|string $balance
     * @var int|string $txCount
     *                 }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 reciver = 1;</code>.
     *
     * @return int
     */
    public function getReciver(): int
    {
        return $this->reciver;
    }

    /**
     * Generated from protobuf field <code>int64 reciver = 1;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setReciver($var): AddrOverview
    {
        GPBUtil::checkInt64($var);
        $this->reciver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     *
     * @return int
     */
    public function getBalance(): int
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>int64 balance = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setBalance($var): AddrOverview
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 3;</code>.
     *
     * @return int
     */
    public function getTxCount(): int
    {
        return $this->txCount;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setTxCount($var): AddrOverview
    {
        GPBUtil::checkInt64($var);
        $this->txCount = $var;

        return $this;
    }
}
