<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.AssetsWithdraw</code>.
 */
class AssetsWithdraw extends Message
{
    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>.
     */
    protected string $cointoken = '';

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>.
     */
    protected int $amount = 0;

    /**
     * Generated from protobuf field <code>bytes note = 3;</code>.
     */
    protected string $note = '';

    /**
     * Generated from protobuf field <code>string execName = 4;</code>.
     */
    protected string $execName = '';

    /**
     * Generated from protobuf field <code>string to = 5;</code>.
     */
    protected string $to = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $cointoken
     * @var int|string $amount
     * @var string $note
     * @var string $execName
     * @var string $to
     *             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>.
     *
     * @return string
     */
    public function getCointoken(): string
    {
        return $this->cointoken;
    }

    /**
     * Generated from protobuf field <code>string cointoken = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setCointoken(string $var): AssetsWithdraw
    {
        GPBUtil::checkString($var, true);
        $this->cointoken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>.
     *
     * @return int
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setAmount($var): AssetsWithdraw
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes note = 3;</code>.
     *
     * @return string
     */
    public function getNote(): string
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>bytes note = 3;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setNote(string $var): AssetsWithdraw
    {
        GPBUtil::checkString($var, false);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string execName = 4;</code>.
     *
     * @return string
     */
    public function getExecName(): string
    {
        return $this->execName;
    }

    /**
     * Generated from protobuf field <code>string execName = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setExecName(string $var): AssetsWithdraw
    {
        GPBUtil::checkString($var, true);
        $this->execName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to = 5;</code>.
     *
     * @return string
     */
    public function getTo(): string
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>string to = 5;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setTo(string $var): AssetsWithdraw
    {
        GPBUtil::checkString($var, true);
        $this->to = $var;

        return $this;
    }
}
