<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 *批量查询有可能导致数据库崩溃.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.BatchQueryStorage</code>.
 */
class BatchQueryStorage extends Message
{
    /**
     * Generated from protobuf field <code>repeated string txHashs = 1;</code>.
     */
    private RepeatedField $txHashs;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string[]|RepeatedField $txHashs
     *                             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Storage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string txHashs = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getTxHashs(): RepeatedField
    {
        return $this->txHashs;
    }

    /**
     * Generated from protobuf field <code>repeated string txHashs = 1;</code>.
     *
     * @param  string[]|RepeatedField  $var
     * @return $this
     * @throws Exception
     */
    public function setTxHashs($var): BatchQueryStorage
    {
        $arr           = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->txHashs = $arr;

        return $this;
    }
}
