<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Blockchain;

/**
 *区块体信息
 *     txs : 区块上所有交易列表
 *     receipts :区块上所有交易的收据信息列表
 *     mainHash : 主链区块hash，平行链使用
 *     mainHeight :主链区块高度，平行链使用
 *     hash : 本链区块hash
 *     height :本链区块高度.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.BlockBody</code>.
 */
class BlockBody extends Message
{
    /**
     * Generated from protobuf field <code>bytes mainHash = 3;</code>.
     */
    protected string $mainHash = '';

    /**
     * Generated from protobuf field <code>int64 mainHeight = 4;</code>.
     */
    protected int $mainHeight = 0;

    /**
     * Generated from protobuf field <code>bytes hash = 5;</code>.
     */
    protected string $hash = '';

    /**
     * Generated from protobuf field <code>int64 height = 6;</code>.
     */
    protected int $height = 0;

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 1;</code>.
     */
    private RepeatedField $txs;

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ReceiptData receipts = 2;</code>.
     */
    private RepeatedField $receipts;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var Transaction[]|RepeatedField $txs
     * @var ReceiptData[]|RepeatedField $receipts
     * @var string $mainHash
     * @var int|string $mainHeight
     * @var string $hash
     * @var int|string $height
     *                 }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getTxs(): RepeatedField
    {
        return $this->txs;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 1;</code>.
     *
     * @param  Transaction[]|RepeatedField  $var
     * @return $this
     * @throws Exception
     */
    public function setTxs($var): BlockBody
    {
        $arr       = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            Transaction::class);
        $this->txs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ReceiptData receipts = 2;</code>.
     *
     * @return RepeatedField
     */
    public function getReceipts(): RepeatedField
    {
        return $this->receipts;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ReceiptData receipts = 2;</code>.
     *
     * @param  ReceiptData[]|RepeatedField  $var
     * @return $this
     * @throws Exception
     */
    public function setReceipts($var): BlockBody
    {
        $arr            = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            ReceiptData::class);
        $this->receipts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 3;</code>.
     *
     * @return string
     */
    public function getMainHash(): string
    {
        return $this->mainHash;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 3;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setMainHash(string $var): BlockBody
    {
        GPBUtil::checkString($var, false);
        $this->mainHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 4;</code>.
     *
     * @return int
     */
    public function getMainHeight(): int
    {
        return $this->mainHeight;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 4;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setMainHeight($var): BlockBody
    {
        GPBUtil::checkInt64($var);
        $this->mainHeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 5;</code>.
     *
     * @return string
     */
    public function getHash(): string
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 5;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setHash(string $var): BlockBody
    {
        GPBUtil::checkString($var, false);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 6;</code>.
     *
     * @return int
     */
    public function getHeight(): int
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 6;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setHeight($var): BlockBody
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }
}
