<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Blockchain;

/**
 *  通过block hash记录block的操作类型及add/del：1/2.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.BlockSequence</code>
 */
class BlockSequence extends Message
{
    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>.
     */
    protected $Hash = '';

    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>.
     */
    protected $Type = 0;

    /**
     * Constructor.
     *
     * @param  array   $data  {
     *                        Optional. Data for populating the Message object.
     * @var string     $Hash
     * @var int|string $Type
     *                        }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>.
     *
     * @return string
     */
    public function getHash()
    {
        return $this->Hash;
    }

    /**
     * Generated from protobuf field <code>bytes Hash = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->Hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>.
     *
     * @return int|string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>int64 Type = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->Type = $var;

        return $this;
    }
}
