<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Blockchain;

/**
 *  参考Header解释
 * mainHash 平行链上使用的字段，代表这个区块的主链hash.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.Block</code>.
 */
class Block extends Message
{
    /**
     * Generated from protobuf field <code>int64 version = 1;</code>.
     */
    protected int $version = 0;

    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>.
     */
    protected string $parentHash = '';

    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>.
     */
    protected string $txHash = '';

    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>.
     */
    protected string $stateHash = '';

    /**
     * Generated from protobuf field <code>int64 height = 5;</code>.
     */
    protected int $height = 0;

    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>.
     */
    protected int $blockTime = 0;

    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>.
     */
    protected int $difficulty = 0;

    /**
     * Generated from protobuf field <code>bytes mainHash = 12;</code>.
     */
    protected string $mainHash = '';

    /**
     * Generated from protobuf field <code>int64 mainHeight = 13;</code>.
     */
    protected int $mainHeight = 0;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>.
     */
    protected ?Signature $signature = null;

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 7;</code>.
     */
    private RepeatedField $txs;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var int|string $version
     * @var string $parentHash
     * @var string $txHash
     * @var string $stateHash
     * @var int|string $height
     * @var int|string $blockTime
     * @var int $difficulty
     * @var string $mainHash
     * @var int|string $mainHeight
     * @var Signature $signature
     * @var Transaction[]|RepeatedField $txs
     *                                  }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 version = 1;</code>.
     *
     * @return int
     */
    public function getVersion(): int
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 1;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setVersion($var): Block
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>.
     *
     * @return string
     */
    public function getParentHash(): string
    {
        return $this->parentHash;
    }

    /**
     * Generated from protobuf field <code>bytes parentHash = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setParentHash(
        string $var
    ): Block {
        GPBUtil::checkString($var, false);
        $this->parentHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>.
     *
     * @return string
     */
    public function getTxHash(): string
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 3;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setTxHash(string $var): Block
    {
        GPBUtil::checkString($var, false);
        $this->txHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>.
     *
     * @return string
     */
    public function getStateHash(): string
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>bytes stateHash = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setStateHash(string $var): Block
    {
        GPBUtil::checkString($var, false);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 5;</code>.
     *
     * @return int
     */
    public function getHeight(): int
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 5;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setHeight($var): Block
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>.
     *
     * @return int
     */
    public function getBlockTime(): int
    {
        return $this->blockTime;
    }

    /**
     * Generated from protobuf field <code>int64 blockTime = 6;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setBlockTime($var): Block
    {
        GPBUtil::checkInt64($var);
        $this->blockTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>.
     *
     * @return int
     */
    public function getDifficulty(): int
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>uint32 difficulty = 11;</code>.
     *
     * @param  int  $var
     * @return $this
     * @throws Exception
     */
    public function setDifficulty(int $var): Block
    {
        GPBUtil::checkUint32($var);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 12;</code>.
     *
     * @return string
     */
    public function getMainHash(): string
    {
        return $this->mainHash;
    }

    /**
     * Generated from protobuf field <code>bytes mainHash = 12;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setMainHash(string $var): Block
    {
        GPBUtil::checkString($var, false);
        $this->mainHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 13;</code>.
     *
     * @return int
     */
    public function getMainHeight(): int
    {
        return $this->mainHeight;
    }

    /**
     * Generated from protobuf field <code>int64 mainHeight = 13;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setMainHeight($var): Block
    {
        GPBUtil::checkInt64($var);
        $this->mainHeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>.
     *
     * @return Signature|null
     */
    public function getSignature(): ?Signature
    {
        return null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Signature signature = 8;</code>.
     *
     * @param  Signature  $var
     * @return $this
     * @throws Exception
     */
    public function setSignature(Signature $var): Block
    {
        GPBUtil::checkMessage($var, Signature::class);
        $this->signature = $var;

        return $this;
    }

    public function hasSignature(): bool
    {
        return isset($this->signature);
    }

    public function clearSignature()
    {
        unset($this->signature);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 7;</code>.
     *
     * @return RepeatedField
     */
    public function getTxs(): RepeatedField
    {
        return $this->txs;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Transaction txs = 7;</code>.
     *
     * @param  Transaction[]|RepeatedField  $var
     * @return $this
     * @throws Exception
     */
    public function setTxs($var): Block
    {
        $arr       = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            Transaction::class);
        $this->txs = $arr;

        return $this;
    }
}
