<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Blockchain;

/**
 * ChunkInfoMsg 用于消息传递.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ChunkInfoMsg</code>.
 */
class ChunkInfoMsg extends Message
{
    /**
     * Generated from protobuf field <code>bytes chunkHash = 1;</code>.
     */
    protected $chunkHash = '';

    /**
     * Generated from protobuf field <code>int64 start = 2;</code>.
     */
    protected $start = 0;

    /**
     * Generated from protobuf field <code>int64 end = 3;</code>.
     */
    protected $end = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $chunkHash
     * @var int|string $start
     * @var int|string $end
     *                 }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes chunkHash = 1;</code>.
     *
     * @return string
     */
    public function getChunkHash()
    {
        return $this->chunkHash;
    }

    /**
     * Generated from protobuf field <code>bytes chunkHash = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setChunkHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->chunkHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start = 2;</code>.
     *
     * @return int|string
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>int64 start = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end = 3;</code>.
     *
     * @return int|string
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * Generated from protobuf field <code>int64 end = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->end = $var;

        return $this;
    }
}
