<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Blockchain;

/**
 * ChunkRecords.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ChunkRecords</code>.
 */
class ChunkRecords extends Message
{
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ChunkInfo infos = 1;</code>.
     */
    private $infos;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var ChunkInfo[]|RepeatedField $infos
     *                                }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ChunkInfo infos = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getInfos()
    {
        return $this->infos;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.ChunkInfo infos = 1;</code>.
     *
     * @param  ChunkInfo[]|RepeatedField  $var
     * @return $this
     */
    public function setInfos($var)
    {
        $arr         = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            ChunkInfo::class);
        $this->infos = $arr;

        return $this;
    }
}
