<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Blockchain;

/**
 *用于比较最优区块的消息结构.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.CmpBlock</code>
 */
class CmpBlock extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Block block = 1;</code>.
     */
    protected $block = null;

    /**
     * Generated from protobuf field <code>bytes cmpHash = 2;</code>.
     */
    protected $cmpHash = '';

    /**
     * Constructor.
     *
     * @param  array                             $data  {
     *                                                  Optional. Data for populating the Message object.
     * @var \Jason\Chain33\Kernel\Protobuf\Block $block
     * @var string                               $cmpHash
     *                                                  }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Block block = 1;</code>.
     *
     * @return \Jason\Chain33\Kernel\Protobuf\Block|null
     */
    public function getBlock()
    {
        return isset($this->block) ? $this->block : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Block block = 1;</code>.
     *
     * @param  \Jason\Chain33\Kernel\Protobuf\Block  $var
     * @return $this
     */
    public function setBlock($var)
    {
        GPBUtil::checkMessage($var, Block::class);
        $this->block = $var;

        return $this;
    }

    public function hasBlock()
    {
        return isset($this->block);
    }

    public function clearBlock()
    {
        unset($this->block);
    }

    /**
     * Generated from protobuf field <code>bytes cmpHash = 2;</code>.
     *
     * @return string
     */
    public function getCmpHash()
    {
        return $this->cmpHash;
    }

    /**
     * Generated from protobuf field <code>bytes cmpHash = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setCmpHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->cmpHash = $var;

        return $this;
    }
}
