<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ExecAccount</code>.
 */
class ExecAccount extends Message
{
    /**
     * Generated from protobuf field <code>string execer = 1;</code>.
     */
    protected $execer = '';

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account account = 2;</code>.
     */
    protected $account = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $execer
     * @var Account $account
     *              }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string execer = 1;</code>.
     *
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     * Generated from protobuf field <code>string execer = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, true);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account account = 2;</code>.
     *
     * @return Account|null
     */
    public function getAccount()
    {
        return isset($this->account) ? $this->account : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account account = 2;</code>.
     *
     * @param  Account  $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkMessage($var, Account::class);
        $this->account = $var;

        return $this;
    }

    public function hasAccount()
    {
        return isset($this->account);
    }

    public function clearAccount()
    {
        unset($this->account);
    }
}
