<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.GetSeedByPw</code>.
 */
class GetSeedByPw extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string passwd = 1;</code>.
     */
    protected $passwd = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     *     @var string $passwd
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string passwd = 1;</code>.
     *
     * @return string
     */
    public function getPasswd()
    {
        return $this->passwd;
    }

    /**
     * Generated from protobuf field <code>string passwd = 1;</code>.
     *
     * @param  string $var
     * @return $this
     */
    public function setPasswd($var)
    {
        GPBUtil::checkString($var, true);
        $this->passwd = $var;

        return $this;
    }
}
