<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Blockchain;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.HeadersPid</code>.
 */
class HeadersPid extends Message
{
    /**
     * Generated from protobuf field <code>string pid = 1;</code>.
     */
    protected $pid = '';

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Headers headers = 2;</code>.
     */
    protected $headers = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                    Optional. Data for populating the Message object.
     * @var string $pid
     * @var Headers $headers
     *                                                    }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pid = 1;</code>.
     *
     * @return string
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>string pid = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkString($var, true);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Headers headers = 2;</code>.
     *
     * @return Headers|null
     */
    public function getHeaders()
    {
        return isset($this->headers) ? $this->headers : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Headers headers = 2;</code>.
     *
     * @param  Headers  $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, Headers::class);
        $this->headers = $var;

        return $this;
    }

    public function hasHeaders()
    {
        return isset($this->headers);
    }

    public function clearHeaders()
    {
        unset($this->headers);
    }
}
