<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.HexTx</code>.
 */
class HexTx extends Message
{
    /**
     * Generated from protobuf field <code>string tx = 1;</code>.
     */
    protected $tx = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     * @var string    $tx
     *                       }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>.
     *
     * @return string
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkString($var, true);
        $this->tx = $var;

        return $this;
    }
}
