<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.Int32</code>.
 */
class Int32 extends Message
{
    /**
     * Generated from protobuf field <code>int32 data = 1;</code>.
     */
    protected $data = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     * @var int       $data
     *                       }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 data = 1;</code>.
     *
     * @return int
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>int32 data = 1;</code>.
     *
     * @param  int  $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkInt32($var);
        $this->data = $var;

        return $this;
    }
}
