<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Blockchain;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.PushWithStatus</code>.
 */
class PushWithStatus extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq push = 1;</code>.
     */
    protected $push = null;

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>.
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var PushSubscribeReq $push
     * @var int $status
     *          }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq push = 1;</code>.
     *
     * @return PushSubscribeReq|null
     */
    public function getPush()
    {
        return isset($this->push) ? $this->push : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.PushSubscribeReq push = 1;</code>.
     *
     * @param  PushSubscribeReq  $var
     * @return $this
     */
    public function setPush($var)
    {
        GPBUtil::checkMessage($var, PushSubscribeReq::class);
        $this->push = $var;

        return $this;
    }

    public function hasPush()
    {
        return isset($this->push);
    }

    public function clearPush()
    {
        unset($this->push);
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 2;</code>.
     *
     * @param  int  $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }
}
