<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 *根据txhash去状态数据库中查询存储内容.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.QueryStorage</code>.
 */
class QueryStorage extends Message
{
    /**
     * Generated from protobuf field <code>string txHash = 1;</code>.
     */
    protected string $txHash = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $txHash
     *             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Storage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string txHash = 1;</code>.
     *
     * @return string
     */
    public function getTxHash(): string
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>string txHash = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setTxHash(string $var): QueryStorage
    {
        GPBUtil::checkString($var, true);
        $this->txHash = $var;

        return $this;
    }
}
