<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Executor;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReceiptConfig</code>.
 */
class ReceiptConfig extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem prev = 1;</code>.
     */
    protected $prev = null;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem current = 2;</code>.
     */
    protected $current = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                       Optional. Data for populating the Message object.
     * @var ConfigItem $prev
     * @var ConfigItem $current
     *                                                       }
     */
    public function __construct($data = null)
    {
        Executor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem prev = 1;</code>.
     *
     * @return ConfigItem|null
     */
    public function getPrev()
    {
        return isset($this->prev) ? $this->prev : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem prev = 1;</code>.
     *
     * @param  ConfigItem  $var
     * @return $this
     */
    public function setPrev($var)
    {
        GPBUtil::checkMessage($var, ConfigItem::class);
        $this->prev = $var;

        return $this;
    }

    public function hasPrev()
    {
        return isset($this->prev);
    }

    public function clearPrev()
    {
        unset($this->prev);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem current = 2;</code>.
     *
     * @return ConfigItem|null
     */
    public function getCurrent()
    {
        return isset($this->current) ? $this->current : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ConfigItem current = 2;</code>.
     *
     * @param  ConfigItem  $var
     * @return $this
     */
    public function setCurrent($var)
    {
        GPBUtil::checkMessage($var, ConfigItem::class);
        $this->current = $var;

        return $this;
    }

    public function hasCurrent()
    {
        return isset($this->current);
    }

    public function clearCurrent()
    {
        unset($this->current);
    }
}
