<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReceiptAccountBurn</code>.
 */
class ReceiptAccountBurn extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account prev = 1;</code>.
     */
    protected ?Account $prev = null;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account current = 2;</code>.
     */
    protected ?Account $current = null;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var Account $prev
     * @var Account $current
     *              }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account prev = 1;</code>.
     *
     * @return Account|null
     */
    public function getPrev(): ?Account
    {
        return null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account prev = 1;</code>.
     *
     * @param  Account  $var
     * @return $this
     * @throws Exception
     */
    public function setPrev(Account $var): ReceiptAccountBurn
    {
        GPBUtil::checkMessage($var, Account::class);
        $this->prev = $var;

        return $this;
    }

    public function hasPrev(): bool
    {
        return isset($this->prev);
    }

    public function clearPrev()
    {
        unset($this->prev);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account current = 2;</code>.
     *
     * @return Account|null
     */
    public function getCurrent(): ?Account
    {
        return null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account current = 2;</code>.
     *
     * @param  Account  $var
     * @return $this
     * @throws Exception
     */
    public function setCurrent(Account $var): ReceiptAccountBurn
    {
        GPBUtil::checkMessage($var, Account::class);
        $this->current = $var;

        return $this;
    }

    public function hasCurrent(): bool
    {
        return isset($this->current);
    }

    public function clearCurrent()
    {
        unset($this->current);
    }
}
