<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Blockchain;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReceiptCheckTxList</code>.
 */
class ReceiptCheckTxList extends Message
{
    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>.
     */
    private $errs;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                              Optional. Data for populating the Message object.
     *
     * @var string[]|RepeatedField $errs
     *                                                              }
     */
    public function __construct($data = null)
    {
        Blockchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getErrs()
    {
        return $this->errs;
    }

    /**
     * Generated from protobuf field <code>repeated string errs = 1;</code>.
     *
     * @param  string[]|RepeatedField  $var
     *
     * @return $this
     */
    public function setErrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->errs = $arr;

        return $this;
    }
}
