<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReplySeed</code>.
 */
class ReplySeed extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string seed = 1;</code>.
     */
    protected $seed = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     *     @var string $seed
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string seed = 1;</code>.
     *
     * @return string
     */
    public function getSeed()
    {
        return $this->seed;
    }

    /**
     * Generated from protobuf field <code>string seed = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setSeed($var)
    {
        GPBUtil::checkString($var, true);
        $this->seed = $var;

        return $this;
    }
}
