<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReplyStrings</code>.
 */
class ReplyStrings extends Message
{
    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>.
     */
    private $datas;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string[]|RepeatedField $datas
     *                             }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getDatas()
    {
        return $this->datas;
    }

    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>.
     *
     * @param  string[]|RepeatedField  $var
     * @return $this
     */
    public function setDatas($var)
    {
        $arr         = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->datas = $arr;

        return $this;
    }
}
