<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReplyTxInfo</code>.
 */
class ReplyTxInfo extends Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     */
    protected $hash = '';

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     */
    protected $height = 0;

    /**
     * Generated from protobuf field <code>int64 index = 3;</code>.
     */
    protected $index = 0;

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Asset assets = 4;</code>.
     */
    private $assets;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                                                            Optional. Data for populating the Message object.
     *
     * @var string $hash
     * @var int|string $height
     * @var int|string $index
     * @var Asset[]|RepeatedField $assets
     *                                                                                            }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     *
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 index = 3;</code>.
     *
     * @return int|string
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int64 index = 3;</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Asset assets = 4;</code>.
     *
     * @return RepeatedField
     */
    public function getAssets()
    {
        return $this->assets;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.Asset assets = 4;</code>.
     *
     * @param  Asset[]|RepeatedField  $var
     *
     * @return $this
     */
    public function setAssets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            Asset::class);
        $this->assets = $arr;

        return $this;
    }
}
