<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqAllExecBalance</code>.
 */
class ReqAllExecBalance extends Message
{
    /**
     *地址列表.
     * Generated from protobuf field <code>string addr = 1;</code>
     */
    protected $addr = '';

    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     */
    protected $execer = '';

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     */
    protected $stateHash = '';

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     */
    protected $asset_exec = '';

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     */
    protected $asset_symbol = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     * @var string    $addr
     *                       地址列表
     * @var string    $execer
     *                       执行器名称
     * @var string    $stateHash
     * @var string    $asset_exec
     * @var string    $asset_symbol
     *                       }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     *地址列表.
     * Generated from protobuf field <code>string addr = 1;</code>
     *
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     *地址列表.
     * Generated from protobuf field <code>string addr = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, true);
        $this->addr = $var;

        return $this;
    }

    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     *
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, true);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     *
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, true);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     *
     * @return string
     */
    public function getAssetExec()
    {
        return $this->asset_exec;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setAssetExec($var)
    {
        GPBUtil::checkString($var, true);
        $this->asset_exec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     *
     * @return string
     */
    public function getAssetSymbol()
    {
        return $this->asset_symbol;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setAssetSymbol($var)
    {
        GPBUtil::checkString($var, true);
        $this->asset_symbol = $var;

        return $this;
    }
}
