<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 *查询一个地址列表在某个执行器中余额.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqBalance</code>
 */
class ReqBalance extends Message
{
    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     */
    protected $execer = '';

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     */
    protected $stateHash = '';

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     */
    protected $asset_exec = '';

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     */
    protected $asset_symbol = '';

    /**
     *地址列表.
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                              Optional. Data for populating the Message object.
     * @var string[]|RepeatedField $addresses
     *                                                              地址列表
     * @var string $execer
     *                                                              执行器名称
     * @var string $stateHash
     * @var string $asset_exec
     * @var string $asset_symbol
     *                                                              }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     *地址列表.
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     *
     * @return RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     *地址列表.
     * Generated from protobuf field <code>repeated string addresses = 1;</code>
     *
     * @param  string[]|RepeatedField  $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->addresses = $arr;

        return $this;
    }

    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     *
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     *执行器名称.
     * Generated from protobuf field <code>string execer = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, true);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     *
     * @return string
     */
    public function getStateHash()
    {
        return $this->stateHash;
    }

    /**
     * Generated from protobuf field <code>string stateHash = 3;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setStateHash($var)
    {
        GPBUtil::checkString($var, true);
        $this->stateHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     *
     * @return string
     */
    public function getAssetExec()
    {
        return $this->asset_exec;
    }

    /**
     * Generated from protobuf field <code>string asset_exec = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setAssetExec($var)
    {
        GPBUtil::checkString($var, true);
        $this->asset_exec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     *
     * @return string
     */
    public function getAssetSymbol()
    {
        return $this->asset_symbol;
    }

    /**
     * Generated from protobuf field <code>string asset_symbol = 5;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setAssetSymbol($var)
    {
        GPBUtil::checkString($var, true);
        $this->asset_symbol = $var;

        return $this;
    }
}
