<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * 指定交易哈希，查找是否存在.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqCheckTxsExist</code>.
 */
class ReqCheckTxsExist extends Message
{
    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 1;</code>.
     */
    private $txHashes;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string[]|RepeatedField $txHashes
     *                             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getTxHashes()
    {
        return $this->txHashes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes txHashes = 1;</code>.
     *
     * @param  string[]|RepeatedField  $var
     * @return $this
     */
    public function setTxHashes($var)
    {
        $arr            = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->txHashes = $arr;

        return $this;
    }
}
