<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqHash</code>.
 */
class ReqHash extends Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     */
    protected $hash = '';

    /**
     * Generated from protobuf field <code>bool upgrade = 2;</code>.
     */
    protected $upgrade = false;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     * @var string    $hash
     * @var bool      $upgrade
     *                       }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool upgrade = 2;</code>.
     *
     * @return bool
     */
    public function getUpgrade()
    {
        return $this->upgrade;
    }

    /**
     * Generated from protobuf field <code>bool upgrade = 2;</code>.
     *
     * @param  bool  $var
     * @return $this
     */
    public function setUpgrade($var)
    {
        GPBUtil::checkBool($var);
        $this->upgrade = $var;

        return $this;
    }
}
