<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqInt</code>.
 */
class ReqInt extends Message
{
    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     */
    protected $height = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                        Optional. Data for populating the Message object.
     *
     * @var int|string $height
     *                        }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     *
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }
}
