<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqRandHash</code>.
 */
class ReqRandHash extends Message
{
    /**
     * Generated from protobuf field <code>string execName = 1;</code>.
     */
    protected $execName = '';

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     */
    protected $height = 0;

    /**
     * Generated from protobuf field <code>int64 blockNum = 3;</code>.
     */
    protected $blockNum = 0;

    /**
     * Generated from protobuf field <code>bytes hash = 4;</code>.
     */
    protected $hash = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                        Optional. Data for populating the Message object.
     * @var string $execName
     * @var int|string $height
     * @var int|string $blockNum
     * @var string $hash
     *                        }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string execName = 1;</code>.
     *
     * @return string
     */
    public function getExecName()
    {
        return $this->execName;
    }

    /**
     * Generated from protobuf field <code>string execName = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setExecName($var)
    {
        GPBUtil::checkString($var, true);
        $this->execName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     *
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 2;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blockNum = 3;</code>.
     *
     * @return int|string
     */
    public function getBlockNum()
    {
        return $this->blockNum;
    }

    /**
     * Generated from protobuf field <code>int64 blockNum = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setBlockNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->blockNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 4;</code>.
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 4;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, false);
        $this->hash = $var;

        return $this;
    }
}
