<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqString</code>.
 */
class ReqString extends Message
{
    /**
     * Generated from protobuf field <code>string data = 1;</code>.
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     * @var string    $data
     *                       }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string data = 1;</code>.
     *
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, true);
        $this->data = $var;

        return $this;
    }
}
