<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.ReqTokenPreCreate</code>.
 */
class ReqTokenPreCreate extends Message
{
    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>.
     */
    protected $creator_addr = '';

    /**
     * Generated from protobuf field <code>string name = 2;</code>.
     */
    protected $name = '';

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>.
     */
    protected $symbol = '';

    /**
     * Generated from protobuf field <code>string introduction = 4;</code>.
     */
    protected $introduction = '';

    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>.
     */
    protected $owner_addr = '';

    /**
     * Generated from protobuf field <code>int64 total = 6;</code>.
     */
    protected $total = 0;

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>.
     */
    protected $price = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                        Optional. Data for populating the Message object.
     *
     * @var string $creator_addr
     * @var string $name
     * @var string $symbol
     * @var string $introduction
     * @var string $owner_addr
     * @var int|string $total
     * @var int|string $price
     *                        }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>.
     *
     * @return string
     */
    public function getCreatorAddr()
    {
        return $this->creator_addr;
    }

    /**
     * Generated from protobuf field <code>string creator_addr = 1;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setCreatorAddr($var)
    {
        GPBUtil::checkString($var, true);
        $this->creator_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>.
     *
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setSymbol($var)
    {
        GPBUtil::checkString($var, true);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string introduction = 4;</code>.
     *
     * @return string
     */
    public function getIntroduction()
    {
        return $this->introduction;
    }

    /**
     * Generated from protobuf field <code>string introduction = 4;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setIntroduction($var)
    {
        GPBUtil::checkString($var, true);
        $this->introduction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>.
     *
     * @return string
     */
    public function getOwnerAddr()
    {
        return $this->owner_addr;
    }

    /**
     * Generated from protobuf field <code>string owner_addr = 5;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setOwnerAddr($var)
    {
        GPBUtil::checkString($var, true);
        $this->owner_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 6;</code>.
     *
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 6;</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>.
     *
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>.
     *
     * @param  int|string  $var
     *
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }
}
