<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * 环签名中的一组签名数据.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.RingSignatureItem</code>
 */
class RingSignatureItem extends Message
{
    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>.
     */
    private $pubkey;

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>.
     */
    private $signature;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                              Optional. Data for populating the Message object.
     *
     * @var string[]|RepeatedField $pubkey
     * @var string[]|RepeatedField $signature
     *                                                              }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     * Generated from protobuf field <code>repeated bytes pubkey = 1;</code>.
     *
     * @param  string[]|RepeatedField  $var
     *
     * @return $this
     */
    public function setPubkey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->pubkey = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>.
     *
     * @return RepeatedField
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>.
     *
     * @param  string[]|RepeatedField  $var
     *
     * @return $this
     */
    public function setSignature($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->signature = $arr;

        return $this;
    }
}
