<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;

/**
 * 环签名类型时，签名字段存储的环签名信息.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.RingSignature</code>
 */
class RingSignature extends Message
{
    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.RingSignatureItem items = 1;</code>.
     */
    private $items;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                                                                                                        Optional. Data for populating the Message object.
     *
     * @var RingSignatureItem[]|RepeatedField $items
     *                                                                                                        }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.RingSignatureItem items = 1;</code>.
     *
     * @return RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .Jason.Chain33.Kernel.Protobuf.RingSignatureItem items = 1;</code>.
     *
     * @param  RingSignatureItem[]|RepeatedField  $var
     *
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE,
            RingSignatureItem::class);
        $this->items = $arr;

        return $this;
    }
}
