<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Common;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.TimeStatus</code>.
 */
class TimeStatus extends Message
{
    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>.
     */
    protected $ntpTime = '';

    /**
     * Generated from protobuf field <code>string localTime = 2;</code>.
     */
    protected $localTime = '';

    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>.
     */
    protected $diff = 0;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                        Optional. Data for populating the Message object.
     * @var string $ntpTime
     * @var string $localTime
     * @var int|string $diff
     *                        }
     */
    public function __construct($data = null)
    {
        Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>.
     *
     * @return string
     */
    public function getNtpTime()
    {
        return $this->ntpTime;
    }

    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setNtpTime($var)
    {
        GPBUtil::checkString($var, true);
        $this->ntpTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string localTime = 2;</code>.
     *
     * @return string
     */
    public function getLocalTime()
    {
        return $this->localTime;
    }

    /**
     * Generated from protobuf field <code>string localTime = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setLocalTime($var)
    {
        GPBUtil::checkString($var, true);
        $this->localTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>.
     *
     * @return int|string
     */
    public function getDiff()
    {
        return $this->diff;
    }

    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setDiff($var)
    {
        GPBUtil::checkInt64($var);
        $this->diff = $var;

        return $this;
    }
}
