<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.TxResult</code>.
 */
class TxResult extends Message
{
    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     */
    protected $height = 0;

    /**
     * Generated from protobuf field <code>int32 index = 2;</code>.
     */
    protected $index = 0;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 3;</code>.
     */
    protected $tx = null;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receiptdate = 4;</code>.
     */
    protected $receiptdate = null;

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     */
    protected $blocktime = 0;

    /**
     * Generated from protobuf field <code>string actionName = 6;</code>.
     */
    protected $actionName = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var int|string $height
     * @var int $index
     * @var Transaction $tx
     * @var ReceiptData $receiptdate
     * @var int|string $blocktime
     * @var string $actionName
     *             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     *
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 1;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 index = 2;</code>.
     *
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int32 index = 2;</code>.
     *
     * @param  int  $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 3;</code>.
     *
     * @return Transaction|null
     */
    public function getTx()
    {
        return isset($this->tx) ? $this->tx : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 3;</code>.
     *
     * @param  Transaction  $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkMessage($var, Transaction::class);
        $this->tx = $var;

        return $this;
    }

    public function hasTx()
    {
        return isset($this->tx);
    }

    public function clearTx()
    {
        unset($this->tx);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receiptdate = 4;</code>.
     *
     * @return ReceiptData|null
     */
    public function getReceiptdate()
    {
        return isset($this->receiptdate) ? $this->receiptdate : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receiptdate = 4;</code>.
     *
     * @param  ReceiptData  $var
     * @return $this
     */
    public function setReceiptdate($var)
    {
        GPBUtil::checkMessage($var, ReceiptData::class);
        $this->receiptdate = $var;

        return $this;
    }

    public function hasReceiptdate()
    {
        return isset($this->receiptdate);
    }

    public function clearReceiptdate()
    {
        unset($this->receiptdate);
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     *
     * @return int|string
     */
    public function getBlocktime()
    {
        return $this->blocktime;
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     *
     * @param  int|string  $var
     * @return $this
     */
    public function setBlocktime($var)
    {
        GPBUtil::checkInt64($var);
        $this->blocktime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actionName = 6;</code>.
     *
     * @return string
     */
    public function getActionName()
    {
        return $this->actionName;
    }

    /**
     * Generated from protobuf field <code>string actionName = 6;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setActionName($var)
    {
        GPBUtil::checkString($var, true);
        $this->actionName = $var;

        return $this;
    }
}
