<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.UserWrite</code>.
 */
class UserWrite extends Message
{
    /**
     * Generated from protobuf field <code>string topic = 1;</code>.
     */
    protected $topic = '';

    /**
     * Generated from protobuf field <code>string content = 2;</code>.
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $topic
     * @var string $content
     *             }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>.
     *
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 1;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, true);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, true);
        $this->content = $var;

        return $this;
    }
}
