<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 *钱包模块存贮的账户信息
 *   privkey : 账户地址对应的私钥
 *   label :账户地址对应的标签
 *   addr :账户地址
 *   timeStamp :创建账户时的时标.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletAccountStore</code>
 */
class WalletAccountStore extends Message
{
    /**
     * Generated from protobuf field <code>string privkey = 1;</code>.
     */
    protected $privkey = '';

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     */
    protected $label = '';

    /**
     * Generated from protobuf field <code>string addr = 3;</code>.
     */
    protected $addr = '';

    /**
     * Generated from protobuf field <code>string timeStamp = 4;</code>.
     */
    protected $timeStamp = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var string $privkey
     * @var string $label
     * @var string $addr
     * @var string $timeStamp
     *                       }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string privkey = 1;</code>.
     *
     * @return string
     */
    public function getPrivkey()
    {
        return $this->privkey;
    }

    /**
     * Generated from protobuf field <code>string privkey = 1;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setPrivkey($var)
    {
        GPBUtil::checkString($var, true);
        $this->privkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, true);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addr = 3;</code>.
     *
     * @return string
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * Generated from protobuf field <code>string addr = 3;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, true);
        $this->addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timeStamp = 4;</code>.
     *
     * @return string
     */
    public function getTimeStamp()
    {
        return $this->timeStamp;
    }

    /**
     * Generated from protobuf field <code>string timeStamp = 4;</code>.
     *
     * @param  string  $var
     *
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkString($var, true);
        $this->timeStamp = $var;

        return $this;
    }
}
