<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 *钱包模块存贮的tx交易详细信息
 *   tx : tx交易信息
 *   receipt :交易收据信息
 *   height :交易所在的区块高度
 *   index :交易所在区块中的索引
 *   blocktime :交易所在区块的时标
 *   amount :交易量
 *   fromaddr :交易打出地址
 *   txhash : 交易对应的哈希值
 *   actionName  :交易对应的函数调用
 *   payload: 保存额外的一些信息，主要是给插件使用.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletTxDetail</code>.
 */
class WalletTxDetail extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>.
     */
    protected ?Transaction $tx = null;

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>.
     */
    protected ?ReceiptData $receipt = null;

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>.
     */
    protected int $height = 0;

    /**
     * Generated from protobuf field <code>int64 index = 4;</code>.
     */
    protected int $index = 0;

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     */
    protected int $blocktime = 0;

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>.
     */
    protected int $amount = 0;

    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>.
     */
    protected string $fromaddr = '';

    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>.
     */
    protected string $txhash = '';

    /**
     * Generated from protobuf field <code>string actionName = 9;</code>.
     */
    protected string $actionName = '';

    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>.
     */
    protected string $payload = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var Transaction $tx
     * @var ReceiptData $receipt
     * @var int|string $height
     * @var int|string $index
     * @var int|string $blocktime
     * @var int|string $amount
     * @var string $fromaddr
     * @var string $txhash
     * @var string $actionName
     * @var string $payload
     *             }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>.
     *
     * @return Transaction|null
     */
    public function getTx(): ?Transaction
    {
        return $this->tx ?? null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Transaction tx = 1;</code>.
     *
     * @param  Transaction  $var
     * @return $this
     * @throws Exception
     */
    public function setTx(Transaction $var): WalletTxDetail
    {
        GPBUtil::checkMessage($var, Transaction::class);
        $this->tx = $var;

        return $this;
    }

    public function hasTx(): bool
    {
        return isset($this->tx);
    }

    public function clearTx()
    {
        unset($this->tx);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>.
     *
     * @return ReceiptData|null
     */
    public function getReceipt(): ?ReceiptData
    {
        return $this->receipt ?? null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.ReceiptData receipt = 2;</code>.
     *
     * @param  ReceiptData  $var
     * @return $this
     * @throws Exception
     */
    public function setReceipt(ReceiptData $var): WalletTxDetail
    {
        GPBUtil::checkMessage($var, ReceiptData::class);
        $this->receipt = $var;

        return $this;
    }

    public function hasReceipt(): bool
    {
        return isset($this->receipt);
    }

    public function clearReceipt()
    {
        unset($this->receipt);
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>.
     *
     * @return int
     */
    public function getHeight(): int
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int64 height = 3;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setHeight($var): WalletTxDetail
    {
        GPBUtil::checkInt64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 index = 4;</code>.
     *
     * @return int
     */
    public function getIndex(): int
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int64 index = 4;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setIndex($var): WalletTxDetail
    {
        GPBUtil::checkInt64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     *
     * @return int
     */
    public function getBlocktime(): int
    {
        return $this->blocktime;
    }

    /**
     * Generated from protobuf field <code>int64 blocktime = 5;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setBlocktime($var): WalletTxDetail
    {
        GPBUtil::checkInt64($var);
        $this->blocktime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>.
     *
     * @return int
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>.
     *
     * @param  int|string  $var
     * @return $this
     * @throws Exception
     */
    public function setAmount($var): WalletTxDetail
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>.
     *
     * @return string
     */
    public function getFromaddr(): string
    {
        return $this->fromaddr;
    }

    /**
     * Generated from protobuf field <code>string fromaddr = 7;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setFromaddr(string $var): WalletTxDetail
    {
        GPBUtil::checkString($var, true);
        $this->fromaddr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>.
     *
     * @return string
     */
    public function getTxhash(): string
    {
        return $this->txhash;
    }

    /**
     * Generated from protobuf field <code>bytes txhash = 8;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setTxhash(string $var): WalletTxDetail
    {
        GPBUtil::checkString($var, false);
        $this->txhash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actionName = 9;</code>.
     *
     * @return string
     */
    public function getActionName(): string
    {
        return $this->actionName;
    }

    /**
     * Generated from protobuf field <code>string actionName = 9;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setActionName(string $var): WalletTxDetail
    {
        GPBUtil::checkString($var, true);
        $this->actionName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>.
     *
     * @return string
     */
    public function getPayload(): string
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 10;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setPayload(string $var): WalletTxDetail
    {
        GPBUtil::checkString($var, false);
        $this->payload = $var;

        return $this;
    }
}
