<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 *钱包当前的状态
 *   isWalletLock : 钱包是否锁状态，true锁定，false解锁
 *   isAutoMining :钱包是否开启挖矿功能，true开启挖矿，false关闭挖矿
 *   isHasSeed : 钱包是否有种子，true已有，false没有
 *   isTicketLock :钱包挖矿买票锁状态，true锁定，false解锁，只能用于挖矿转账.
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletStatus</code>.
 */
class WalletStatus extends Message
{
    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>.
     */
    protected bool $isWalletLock = false;

    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>.
     */
    protected bool $isAutoMining = false;

    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>.
     */
    protected bool $isHasSeed = false;

    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>.
     */
    protected bool $isTicketLock = false;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var bool $isWalletLock
     * @var bool $isAutoMining
     * @var bool $isHasSeed
     * @var bool $isTicketLock
     *           }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>.
     *
     * @return bool
     */
    public function getIsWalletLock(): bool
    {
        return $this->isWalletLock;
    }

    /**
     * Generated from protobuf field <code>bool isWalletLock = 1;</code>.
     *
     * @param  bool  $var
     * @return $this
     * @throws Exception
     */
    public function setIsWalletLock(bool $var): WalletStatus
    {
        GPBUtil::checkBool($var);
        $this->isWalletLock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>.
     *
     * @return bool
     */
    public function getIsAutoMining(): bool
    {
        return $this->isAutoMining;
    }

    /**
     * Generated from protobuf field <code>bool isAutoMining = 2;</code>.
     *
     * @param  bool  $var
     * @return $this
     * @throws Exception
     */
    public function setIsAutoMining(bool $var): WalletStatus
    {
        GPBUtil::checkBool($var);
        $this->isAutoMining = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>.
     *
     * @return bool
     */
    public function getIsHasSeed(): bool
    {
        return $this->isHasSeed;
    }

    /**
     * Generated from protobuf field <code>bool isHasSeed = 3;</code>.
     *
     * @param  bool  $var
     * @return $this
     * @throws Exception
     */
    public function setIsHasSeed(bool $var): WalletStatus
    {
        GPBUtil::checkBool($var);
        $this->isHasSeed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>.
     *
     * @return bool
     */
    public function getIsTicketLock(): bool
    {
        return $this->isTicketLock;
    }

    /**
     * Generated from protobuf field <code>bool isTicketLock = 4;</code>.
     *
     * @param  bool  $var
     * @return $this
     * @throws Exception
     */
    public function setIsTicketLock(bool $var): WalletStatus
    {
        GPBUtil::checkBool($var);
        $this->isTicketLock = $var;

        return $this;
    }
}
