<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Exception;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletAccount</code>.
 */
class WalletAccount extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     */
    protected ?Account $acc = null;

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     */
    protected string $label = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var Account $acc
     * @var string $label
     *             }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     *
     * @return Account|null
     */
    public function getAcc(): ?Account
    {
        return $this->acc ?? null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     *
     * @param  Account  $var
     * @return $this
     * @throws Exception
     */
    public function setAcc(Account $var): WalletAccount
    {
        GPBUtil::checkMessage($var, Account::class);
        $this->acc = $var;

        return $this;
    }

    public function hasAcc(): bool
    {
        return isset($this->acc);
    }

    public function clearAcc()
    {
        unset($this->acc);
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @return string
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     * @throws Exception
     */
    public function setLabel(string $var): WalletAccount
    {
        GPBUtil::checkString($var, true);
        $this->label = $var;

        return $this;
    }
}
