<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

namespace Jason\Chain33\Kernel\Protobuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Wallet;

/**
 * Generated from protobuf message <code>Jason.Chain33.Kernel.Protobuf.WalletAccount</code>.
 */
class WalletAccount extends Message
{
    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     */
    protected $acc = null;

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     */
    protected $label = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @var Account $acc
     * @var string $label
     *             }
     */
    public function __construct($data = null)
    {
        Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     *
     * @return Account|null
     */
    public function getAcc()
    {
        return isset($this->acc) ? $this->acc : null;
    }

    /**
     * Generated from protobuf field <code>.Jason.Chain33.Kernel.Protobuf.Account acc = 1;</code>.
     *
     * @param  Account  $var
     * @return $this
     */
    public function setAcc($var)
    {
        GPBUtil::checkMessage($var, Account::class);
        $this->acc = $var;

        return $this;
    }

    public function hasAcc()
    {
        return isset($this->acc);
    }

    public function clearAcc()
    {
        unset($this->acc);
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 2;</code>.
     *
     * @param  string  $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, true);
        $this->label = $var;

        return $this;
    }
}
